name: Maven Build

on:
  pull_request:
    branches:
      - main

jobs:

  build-and-test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run Maven to Build, Test, Verify and Deploy
        run: mvn --batch-mode --update-snapshots deploy site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Compute SHA for the Build
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Attach Artifact
        uses: actions/upload-artifact@v3
        with:
          name: All-Artifacts-${{ steps.vars.outputs.sha_short }}
          path: |
            target/*.jar
      - name: Attach Surefire Reports
        uses: actions/upload-artifact@v3
        with:
          name: surefire-reports-${{ steps.vars.outputs.sha_short }}
          path: |
            target/surefire-reports/*
      - name: Attach Site
        uses: actions/upload-artifact@v3
        with:
          name: site-${{ steps.vars.outputs.sha_short }}
          path: |
            target/site/*
