name: Publish Maven Site

on:
  push:
#    branches:
#      - main

jobs:

  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          server-id: github_pages
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Run Maven to Build, Test, Verify and Deploy
        run: git config user.email "bot@example.com" && git config user.name "My GitHub Bot" && mvn --batch-mode --update-snapshots clean site site:stage scm-publish:publish-scm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_USERNAME: git
          MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
